export const WANTED_EXERCISES = [
    // ==================== CHEST ====================
    'Bench Press',
    'Incline Bench Press',
    'Decline Bench Press',
    'Flat Dumbbell Press',
    'Dumbbell Bench Press',
    'Incline Dumbbell Press',
    'Decline Dumbbell Press',
    'Close Grip Bench Press',
    'Wide Grip Bench Press',
    'Machine Chest Press',
    'Smith Machine Bench Press',

    // Push Ups
    'Push Up',
    'Wide Grip Push Up',
    'Close Grip Push Up',
    'Diamond Push Up',
    'Incline Push Up',
    'Decline Push Up',
    'Knee Push Up',
    'Archer Push Up',
    'Pseudo Planche Push Up',
    'Pike Push Up',
    'Handstand Push Up',
    'Explosive Push Up',
    'Clap Push Up',
    'One Arm Push Up',
    'Staggered Push Up',
    'Spiderman Push Up',
    'Shoulder Tap Push Up',
    'Hindu Push Up',

    // Chest Fly
    'Dumbbell Fly',
    'Incline Dumbbell Fly',
    'Decline Dumbbell Fly',
    'Cable Fly',
    'Low Cable Fly',
    'High Cable Fly',
    'Cable Crossover',
    'Machine Chest Fly',
    'Chest Dip',
    'Assisted Chest Dip',

    // ==================== BACK ====================
    'Pull Up',
    'Wide Grip Pull Up',
    'Close Grip Pull Up',
    'Neutral Grip Pull Up',
    'Archer Pull Up',
    'Commando Pull Up',
    'Chest To Bar Pull Up',
    'Muscle Up',
    'Assisted Pull Up',
    'Negative Pull Up',
    'Weighted Pull Up',

    // Chin Ups
    'Chin Up',
    'Close Grip Chin Up',
    'Neutral Grip Chin Up',
    'Assisted Chin Up',
    'Negative Chin Up',
    'Weighted Chin Up',

    // Pulldowns
    'Lat Pulldown',
    'Wide Grip Lat Pulldown',
    'Close Grip Lat Pulldown',
    'Reverse Grip Lat Pulldown',
    'Neutral Grip Lat Pulldown',
    'Single Arm Lat Pulldown',
    'Behind Neck Lat Pulldown',

    // Rows
    'Barbell Row',
    'Pendlay Row',
    'Yates Row',
    'Dumbbell Row',
    'One Arm Dumbbell Row',
    'Seated Cable Row',
    'Close Grip Seated Cable Row',
    'Wide Grip Seated Cable Row',
    'T Bar Row',
    'Chest Supported Row',
    'Machine Row',
    'Single Arm Cable Row',
    'Inverted Row',
    'Wide Grip Inverted Row',
    'Close Grip Inverted Row',
    'Meadows Row',

    // Other Back
    'Straight Arm Pulldown',
    'Dumbbell Pullover',
    'Barbell Pullover',
    'Face Pull',
    'Deadlift',
    'Rack Pull',

    // ==================== SHOULDERS ====================
    'Overhead Press',
    'Barbell Shoulder Press',
    'Dumbbell Shoulder Press',
    'Seated Dumbbell Shoulder Press',
    'Arnold Press',
    'Push Press',
    'Machine Shoulder Press',
    'Smith Machine Shoulder Press',

    // Lateral Raises
    'Lateral Raise',
    'Dumbbell Lateral Raise',
    'Cable Lateral Raise',
    'Single Arm Cable Lateral Raise',
    'Machine Lateral Raise',
    'Leaning Lateral Raise',

    // Front Delts
    'Front Raise',
    'Dumbbell Front Raise',
    'Cable Front Raise',
    'Plate Front Raise',
    'Barbell Front Raise',

    // Rear Delts
    'Reverse Fly',
    'Dumbbell Reverse Fly',
    'Cable Reverse Fly',
    'Rear Delt Fly',
    'Machine Rear Delt Fly',
    'Bent Over Rear Delt Fly',
    'Face Pull',

    // ==================== BICEPS ====================
    'Barbell Curl',
    'EZ Bar Curl',
    'Dumbbell Curl',
    'Alternating Dumbbell Curl',
    'Hammer Curl',
    'Cross Body Hammer Curl',
    'Incline Dumbbell Curl',
    'Preacher Curl',
    'Dumbbell Preacher Curl',
    'Concentration Curl',
    'Cable Curl',
    'Single Arm Cable Curl',
    'Bayesian Curl',
    'Spider Curl',
    'Zottman Curl',
    'Reverse Curl',
    'Drag Curl',

    // ==================== TRICEPS ====================
    'Tricep Pushdown',
    'Rope Tricep Pushdown',
    'Straight Bar Tricep Pushdown',
    'Reverse Grip Tricep Pushdown',
    'Single Arm Tricep Pushdown',
    'Overhead Tricep Extension',
    'Rope Overhead Tricep Extension',
    'Dumbbell Overhead Tricep Extension',
    'Single Arm Dumbbell Tricep Extension',
    'Cable Overhead Tricep Extension',
    'Skull Crusher',
    'EZ Bar Skull Crusher',
    'Dumbbell Skull Crusher',
    'Close Grip Bench Press',
    'Tricep Dip',
    'Bench Dip',
    'Assisted Tricep Dip',
    'Diamond Push Up',

    // ==================== QUADS ====================
    'Squat',
    'Barbell Back Squat',
    'Front Squat',
    'Goblet Squat',
    'Hack Squat',
    'Leg Press',
    'Single Leg Press',
    'Leg Extension',
    'Walking Lunge',
    'Forward Lunge',
    'Reverse Lunge',
    'Lateral Lunge',
    'Bulgarian Split Squat',
    'Split Squat',
    'Step Up',
    'Weighted Step Up',
    'Sissy Squat',
    'Wall Sit',
    'Jump Squat',

    // ==================== HAMSTRINGS ====================
    'Romanian Deadlift',
    'Dumbbell Romanian Deadlift',
    'Stiff Leg Deadlift',
    'Sumo Deadlift',
    'Conventional Deadlift',
    'Single Leg Romanian Deadlift',
    'Leg Curl',
    'Lying Leg Curl',
    'Seated Leg Curl',
    'Standing Leg Curl',
    'Single Leg Curl',
    'Nordic Hamstring Curl',
    'Assisted Nordic Hamstring Curl',
    'Good Morning',
    'Glute Ham Raise',

    // ==================== GLUTES ====================
    'Hip Thrust',
    'Barbell Hip Thrust',
    'Dumbbell Hip Thrust',
    'Single Leg Hip Thrust',
    'Glute Bridge',
    'Barbell Glute Bridge',
    'Single Leg Glute Bridge',
    'Cable Kickback',
    'Glute Kickback',
    'Donkey Kick',
    'Fire Hydrant',
    'Hip Abduction',
    'Cable Hip Abduction',
    'Banded Hip Abduction',
    'Sumo Squat',
    'Curtsy Lunge',

    // ==================== CALVES ====================
    'Standing Calf Raise',
    'Seated Calf Raise',
    'Single Leg Calf Raise',
    'Donkey Calf Raise',
    'Leg Press Calf Raise',
    'Smith Machine Calf Raise',
    'Calf Raise',
    'Tibialis Raise',

    // ==================== ABS / CORE ====================
    'Crunch',
    'Bicycle Crunch',
    'Reverse Crunch',
    'Cable Crunch',
    'Weighted Crunch',
    'Sit Up',
    'Decline Sit Up',
    'Russian Twist',
    'Leg Raise',
    'Lying Leg Raise',
    'Hanging Leg Raise',
    'Hanging Knee Raise',
    'Knee Raise',
    'Reverse Leg Raise',
    'V Up',
    'Toe Touch',
    'Heel Touch',
    'Flutter Kicks',
    'Scissor Kicks',
    'Mountain Climber',
    'Dead Bug',
    'Bird Dog',
    'Ab Wheel Rollout',

    // Planks
    'Plank',
    'Forearm Plank',
    'High Plank',
    'Straight Arm Plank',
    'Knee Plank',
    'Side Plank',
    'Side Plank Hip Dip',
    'Side Plank Reach Through',
    'Reverse Plank',
    'Plank Shoulder Tap',
    'Plank Hip Dip',
    'Plank Up Down',
    'Plank Jack',
    'Plank Knee To Elbow',
    'Spiderman Plank',
    'Mountain Climber Plank',
    'Extended Plank',
    'RKC Plank',
    'Weighted Plank',
    'Single Leg Plank',
    'Single Arm Plank',
    'Plank To Push Up',
    'Bear Plank',
    'Commando Plank',

    // ==================== FOREARMS / GRIP ====================
    'Wrist Curl',
    'Reverse Wrist Curl',
    'Reverse Curl',
    'Hammer Curl',
    "Farmer's Carry",
    'Suitcase Carry',
    'Farmer Walk',
    'Dead Hang',
    'Towel Hang',
    'Plate Pinch',
    'Wrist Roller',

    // ==================== LOWER BACK ====================
    'Back Extension',
    'Hyperextension',
    'Weighted Back Extension',
    '45 Degree Back Extension',
    'Good Morning',
    'Bird Dog',
    'Superman',
    'Superman Hold',

    // ==================== FULL BODY ====================
    'Burpee',
    'Burpee Box Jump',
    'Burpee Broad Jump',
    'Burpee Pull Up',
    'Jump Squat',
    'Bodyweight Squat',
    'Air Squat',
    'Prisoner Squat',
    'Kettlebell Swing',
    'Kettlebell Clean',
    'Kettlebell Snatch',
    'Kettlebell Clean and Press',
    'Turkish Get Up',
    'Thruster',
    'Dumbbell Thruster',
    'Barbell Thruster',
    'Man Maker',
    'Renegade Row',
    'Dumbbell Clean and Press',
    'Barbell Clean and Press',
    'Power Clean',
    'Hang Clean',
    'Clean and Jerk',
    'Snatch',
    'Power Snatch',
    'Hang Snatch',
    'Dumbbell Snatch',
    'Dumbbell Clean',
    'Dumbbell Complex',
    'Barbell Complex',
    'Bear Crawl',
    'Bear Crawl Shoulder Tap',
    'Crab Walk',
    'Inchworm',
    'Inchworm Push Up',
    'Sprawl',
    'Broad Jump',
    'Box Jump',
    'Box Jump Over',
    'Burpee Box Jump Over',
    'Wall Ball',
    'Medicine Ball Slam',
    'Medicine Ball Throw',
    'Medicine Ball Rotational Throw',
    'Medicine Ball Chest Pass',
    'Medicine Ball Squat Throw',
    'Battle Rope Slam',
    'Battle Rope Waves',
    'Battle Rope Alternating Waves',
    'Battle Rope Double Arm Slam',
    'Sled Push',
    'Sled Pull',
    'Prowler Push',
    'Farmer Walk',
    'Farmer Carry',
    'Suitcase Carry',
    'Overhead Carry',
    'Front Rack Carry',
    'Walking Lunge',
    'Reverse Lunge',
    'Walking Dumbbell Lunge',
    'Overhead Walking Lunge',
    'Goblet Squat to Press',
    'Squat to Press',
    'Reverse Lunge to Knee Drive',
    'Lunge to Bicep Curl',
    'Lunge to Press',
    'Step Up to Knee Drive',
    'Dumbbell Devil Press',
    'Devil Press',
    'Bear Complex',
    'CrossFit Burpee',
    'Muscle Up',
    'Barbell Complex',

    // ==================== CARDIO ====================
    'Running',
    'Walking',
    'Brisk Walking',
    'Jogging',
    'Sprinting',
    'Interval Running',
    'Treadmill Running',
    'Treadmill Walking',
    'Incline Treadmill Walking',
    'Backward Walking',

    // Cycling
    'Cycling',
    'Stationary Cycling',
    'Indoor Cycling',
    'Spin Bike',
    'Air Bike',
    'Assault Bike',
    'Bike Sprint',
    'Stationary Bike Intervals',

    // Stair / Incline
    'Stair Climbing',
    'Stairmaster',
    'Stair Running',
    'Step Mill',
    'Incline Walking',

    // Jump Rope
    'Jump Rope',
    'Single Under',
    'Double Unders',
    'Alternating Foot Jump Rope',
    'High Knee Jump Rope',
    'Cross Over Jump Rope',

    // Jumping / Plyometrics
    'Jumping Jack',
    'Star Jump',
    'Seal Jack',
    'Cross Jack',
    'Half Jack',
    'High Knees',
    'Butt Kicks',
    'Fast Feet',
    'Skater Jumps',
    'Lateral Hops',
    'Forward Hops',
    'Single Leg Hops',
    'Broad Jump',
    'Box Jump',
    'Box Jump Over',
    'Depth Jump',
    'Tuck Jump',
    'Split Jump',
    'Jumping Lunge',
    'Jump Squat',
    '180 Jump',
    'Burpee',
    'Burpee Broad Jump',

    // HIIT / Conditioning
    'Mountain Climber',
    'Cross Body Mountain Climber',
    'Slow Mountain Climber',
    'Plank Jack',
    'Burpee',
    'Half Burpee',
    'Sprawl',
    'High Knees Sprint',
    'Butt Kick Sprint',
    'Bear Crawl',
    'Crab Walk',
    'Inchworm',
    'Shuttle Run',
    'Suicide Run',
    'Cone Drill',
    'Agility Ladder',
    'Lateral Shuffle',
    'Carioca',
    'Backpedal',
    'Acceleration Sprint',
    'Hill Sprint',

    // Rowing
    'Rowing',
    'Indoor Rowing',
    'Rowing Machine',
    'Rowing Sprint',
    'Rowing Intervals',

    // Swimming
    'Swimming',
    'Freestyle Swimming',
    'Breaststroke',
    'Backstroke',
    'Butterfly Stroke',
    'Swimming Intervals',

    // Boxing / Conditioning
    'Shadow Boxing',
    'Heavy Bag',
    'Boxing',
    'Kickboxing',
    'Jumping Rope Boxing',

    // Low Impact Cardio
    'Elliptical',
    'Elliptical Trainer',
    'Cross Trainer',
    'Recumbent Bike',
    'Stepper',
    'Low Impact Step',
    'Aerobic Step',
    'Marching in Place',

    // Sports / Recreational Cardio
    'Basketball',
    'Football',
    'Soccer',
    'Tennis',
    'Badminton',
    'Volleyball',
    'Swimming Laps',
    'Hiking',
    'Trail Running',
    'Rowing',

    // ==================== MEDITATION ====================
    'Mindfulness Meditation',
    'Breathing Meditation',
    'Guided Meditation',
    'Body Scan Meditation',
    'Visualization Meditation',
    'Loving Kindness Meditation',
    'Gratitude Meditation',
    'Focus Meditation',
    'Walking Meditation',
    'Sleep Meditation',
    'Stress Relief Meditation',
    'Relaxation Meditation',
    'Mantra Meditation',
    'Silent Meditation',
    'Yoga Nidra',

    // ==================== STRETCHING ====================

    // Neck
    'Neck Stretch',
    'Side Neck Stretch',
    'Forward Neck Stretch',
    'Neck Rotation',
    'Chin Tuck',
    'Upper Trapezius Stretch',
    'Levator Scapulae Stretch',

    // Shoulders
    'Shoulder Stretch',
    'Cross Body Shoulder Stretch',
    'Overhead Shoulder Stretch',
    'Doorway Shoulder Stretch',
    'Wall Shoulder Stretch',
    'Shoulder Dislocates',
    'Shoulder Circles',
    'Arm Circles',
    'Wall Angels',
    'Thread the Needle',
    'Childs Pose with Side Reach',

    // Chest
    'Chest Stretch',
    'Doorway Chest Stretch',
    'Wall Chest Stretch',
    'Standing Chest Stretch',
    'Corner Chest Stretch',
    'Kneeling Chest Stretch',
    'Behind the Back Chest Stretch',

    // Upper Back
    'Upper Back Stretch',
    'Standing Upper Back Stretch',
    'Seated Upper Back Stretch',
    'Cat Cow Stretch',
    'Childs Pose',
    'Extended Childs Pose',
    'Thread the Needle',
    'Prayer Stretch',
    'Lat Stretch',
    'Bench Lat Stretch',
    'Standing Lat Stretch',

    // Lats
    'Overhead Lat Stretch',
    'Childs Pose Lat Stretch',
    'Bench Lat Stretch',
    'Standing Side Lat Stretch',
    'Kneeling Lat Stretch',

    // Arms / Biceps
    'Biceps Stretch',
    'Standing Biceps Stretch',
    'Wall Biceps Stretch',
    'Overhead Triceps Stretch',
    'Cross Body Triceps Stretch',
    'Triceps Stretch',
    'Forearm Stretch',
    'Wrist Flexor Stretch',
    'Wrist Extensor Stretch',
    'Prayer Wrist Stretch',
    'Reverse Prayer Stretch',

    // Spine
    'Spinal Twist',
    'Seated Spinal Twist',
    'Supine Spinal Twist',
    'Kneeling Spinal Twist',
    'Open Book Stretch',
    'Cat Cow',
    'Childs Pose',
    'Cobra Stretch',
    'Upward Dog',
    'McKenzie Press Up',

    // Abs / Core
    'Abdominal Stretch',
    'Cobra Stretch',
    'Upward Dog',
    'Standing Abdominal Stretch',
    'Kneeling Abdominal Stretch',
    'Side Bend Stretch',
    'Standing Side Stretch',

    // Hip Flexors
    'Hip Flexor Stretch',
    'Kneeling Hip Flexor Stretch',
    'Low Lunge Stretch',
    'Runner Lunge Stretch',
    'Half Kneeling Hip Flexor Stretch',
    'Standing Hip Flexor Stretch',
    'Couch Stretch',
    'Bulgarian Split Squat Stretch',

    // Hips
    'Hip Stretch',
    '90/90 Hip Stretch',
    '90/90 Hip Switch',
    'Seated Hip Stretch',
    'Figure Four Stretch',
    'Supine Figure Four Stretch',
    'Pigeon Pose',
    'Half Pigeon Pose',
    'Frog Stretch',
    'Butterfly Stretch',
    'Happy Baby Pose',
    'Deep Squat Stretch',
    'Adductor Rock Back',
    'Hip Circles',
    'Fire Hydrant Mobility',

    // Glutes
    'Glute Stretch',
    'Seated Glute Stretch',
    'Standing Glute Stretch',
    'Figure Four Stretch',
    'Standing Figure Four Stretch',
    'Supine Figure Four Stretch',
    'Pigeon Stretch',
    'Pigeon Pose',
    'Knee to Chest Stretch',
    'Double Knee to Chest Stretch',

    // Groin / Adductors
    'Groin Stretch',
    'Butterfly Stretch',
    'Frog Stretch',
    'Seated Straddle Stretch',
    'Side Lunge Stretch',
    'Cossack Squat Stretch',
    'Adductor Stretch',
    'Adductor Rock Back',
    'Standing Adductor Stretch',

    // Quads
    'Quadriceps Stretch',
    'Standing Quad Stretch',
    'Side Lying Quad Stretch',
    'Kneeling Quad Stretch',
    'Couch Stretch',
    'Hip Flexor Quad Stretch',

    // Hamstrings
    'Hamstring Stretch',
    'Standing Hamstring Stretch',
    'Seated Hamstring Stretch',
    'Single Leg Hamstring Stretch',
    'Lying Hamstring Stretch',
    'Band Hamstring Stretch',
    'Wall Hamstring Stretch',
    'Half Split Stretch',
    'Downward Dog',
    'Toe Touch Stretch',

    // Calves
    'Calf Stretch',
    'Standing Calf Stretch',
    'Wall Calf Stretch',
    'Bent Knee Calf Stretch',
    'Straight Leg Calf Stretch',
    'Seated Calf Stretch',
    'Downward Dog Calf Stretch',
    'Single Leg Calf Stretch',

    // Ankles / Feet
    'Ankle Stretch',
    'Ankle Mobility',
    'Ankle Circles',
    'Knee to Wall Ankle Stretch',
    'Calf and Ankle Stretch',
    'Toe Stretch',
    'Foot Stretch',
    'Plantar Fascia Stretch',
    'Toe Extension Stretch',

    // Full Body
    'Full Body Stretch',
    'Standing Full Body Stretch',
    'Floor Full Body Stretch',
    'Worlds Greatest Stretch',
    'Inchworm Stretch',
    'Downward Dog',
    'Upward Dog',
    'Cat Cow',
    'Childs Pose',
    'Happy Baby Pose',
    'Deep Squat Hold',
    'Jefferson Curl',

    // Dynamic Stretching / Warm Up
    'Arm Swings',
    'Arm Circles',
    'Shoulder Circles',
    'Leg Swings',
    'Front to Back Leg Swings',
    'Side to Side Leg Swings',
    'Hip Circles',
    'Ankle Circles',
    'Walking Lunges',
    'Walking Knee Hug',
    'Walking Quad Stretch',
    'Walking Hamstring Stretch',
    'Walking Lunge with Rotation',
    'Worlds Greatest Stretch',
    'Inchworm',
    'Inchworm with Push Up',
    'Frankenstein Walk',
    'Toy Soldier',
    'High Knees',
    'Butt Kicks',
    'Carioca',
    'Lateral Lunge',
    'Cossack Squat',
    'Deep Squat Pry',
    'Spiderman Stretch',
    'Spiderman Stretch with Rotation',
    'Worlds Greatest Stretch with Rotation',

    // Mobility
    '90/90 Hip Mobility',
    '90/90 Hip Switch',
    'Deep Squat Mobility',
    'Deep Squat Pry',
    'Cossack Squat',
    'Ankle Dorsiflexion Stretch',
    'Knee to Wall',
    'Thoracic Rotation',
    'Open Book',
    'Thread the Needle',
    'Cat Cow',
    'Shoulder CARs',
    'Hip CARs',
    'Ankle CARs',
    'Neck CARs',
    'Spinal CARs',
    'Scapular Wall Slides',
    'Wall Angels',
    'Thoracic Extension',
    'Foam Roller Thoracic Extension',
    'Foam Roller Lat Stretch',
    'Foam Roller Quad Stretch',
    'Foam Roller Glute Stretch',

    // ==================== YOGA ====================

    // Standing Poses
    'Mountain Pose',
    'Chair Pose',
    'Warrior I',
    'Warrior II',
    'Warrior III',
    'Reverse Warrior',
    'Extended Side Angle Pose',
    'Triangle Pose',
    'Pyramid Pose',
    'Tree Pose',
    'Eagle Pose',
    'Half Moon Pose',
    'Standing Forward Fold',

    // Seated Poses
    'Easy Pose',
    'Lotus Pose',
    'Half Lotus Pose',
    'Seated Forward Fold',
    'Bound Angle Pose',
    'Staff Pose',
    'Hero Pose',
    'Childs Pose',
    'Cow Face Pose',
    'Head to Knee Pose',

    // Hip / Lower Body
    'Pigeon Pose',
    'Half Pigeon Pose',
    'Happy Baby Pose',
    'Garland Pose',
    'Low Lunge',
    'Lizard Pose',
    'Frog Pose',
    'Reclining Bound Angle Pose',

    // Back / Spine
    'Cat Cow Pose',
    'Cobra Pose',
    'Upward Facing Dog',
    'Downward Facing Dog',
    'Sphinx Pose',
    'Bridge Pose',
    'Locust Pose',
    'Bow Pose',
    'Camel Pose',
    'Fish Pose',
    'Supine Spinal Twist',

    // Balance
    'Tree Pose',
    'Eagle Pose',
    'Warrior III',
    'Dancer Pose',
    'Crow Pose',

    // Restorative / Relaxation
    'Corpse Pose',
    'Childs Pose',
    'Legs Up the Wall',
    'Happy Baby Pose',
    'Reclining Bound Angle Pose',

    // Yoga Flows
    'Sun Salutation',
    'Sun Salutation A',
    'Sun Salutation B',
    'Cat Cow Flow',
    'Vinyasa Flow',
];